<?php
/**
 * Created by xalbert.einsteinx
 * https://www.einsteinium.pro
 * Date: 13.05.2016
 * Time: 17:12
 */

namespace bl\cms\error;

use Yii;

class Module extends \yii\base\Module
{
    public function init()
    {
        $this->registerTranslations();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function registerTranslations()
    {
        Yii::$app->i18n->translations['modules/errorhandler/*'] = [
            'class'          => 'yii\i18n\PhpMessageSource',
            'sourceLanguage' => 'en-US',
            'basePath'       => '@vendor/black-lamp/blcms-error-handler/messages',
            'fileMap'        => [
                'modules/errorhandler/main' => 'main.php'
            ]
        ];
    }
}